In [1]:
print('Hello World')

Hello World


In [2]:
import pandas as pd

data = {
    "Name": ["John", "Alice", "Bob"],
    "Age": [25, 30, 22],
    "Salary": [50000, 60000, 45000]
}

df = pd.DataFrame(data)
print(df)

    Name  Age  Salary
0   John   25   50000
1  Alice   30   60000
2    Bob   22   45000


In [3]:
text_data = [
    "I love this product! It's amazing 😍",
    "Worst experience ever. Totally disappointed.",
    "Average quality, nothing special."
]

print(text_data)

["I love this product! It's amazing 😍", 'Worst experience ever. Totally disappointed.', 'Average quality, nothing special.']


In [4]:
print(df[df["Salary"] > 50000])

    Name  Age  Salary
1  Alice   30   60000


In [11]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')

sentence = "Hi my name is Harshith. I am a Computer Science student."

words = word_tokenize(sentence)

filtered = [w for w in words if w.lower() not in stopwords.words('english')]

print(filtered)

[nltk_data] Error loading punkt: <urlopen error [SSL:
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed:
[nltk_data]     unable to get local issuer certificate (_ssl.c:1081)>
[nltk_data] Error loading punkt_tab: <urlopen error [SSL:
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed:
[nltk_data]     unable to get local issuer certificate (_ssl.c:1081)>
[nltk_data] Error loading stopwords: <urlopen error [SSL:
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed:
[nltk_data]     unable to get local issuer certificate (_ssl.c:1081)>


LookupError: 
**********************************************************************
  Resource 'punkt_tab' not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt_tab')

  For more information see: https://www.nltk.org/data.html

  Attempted to load 'tokenizers/punkt_tab/english/'

  Searched in:
    - '/Users/santhoshkumarv/nltk_data'
    - '/Library/Frameworks/Python.framework/Versions/3.14/nltk_data'
    - '/Library/Frameworks/Python.framework/Versions/3.14/share/nltk_data'
    - '/Library/Frameworks/Python.framework/Versions/3.14/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
    - '/Users/your_username/nltk_data'
**********************************************************************


In [12]:
import ssl
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

try:
    _create_unverified_https_context = ssl._create_unverified_context
    ssl._create_default_https_context = _create_unverified_https_context
except:
    pass

nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')


sentence = "Hi my name is Harshith. I am a Computer Science student."

words = word_tokenize(sentence)

filtered = [w for w in words if w.lower() not in stopwords.words('english')]

print(filtered)

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/santhoshkumarv/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to
[nltk_data]     /Users/santhoshkumarv/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/santhoshkumarv/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


['Hi', 'name', 'Harshith', '.', 'Computer', 'Science', 'student', '.']


In [15]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(words)

print(vectorizer.get_feature_names_out())
print(X.toarray())

['am' 'computer' 'harshith' 'hi' 'is' 'my' 'name' 'science' 'student']
[[0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0 0]
 [0 0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0]]


In [16]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(filtered)

print(vectorizer.get_feature_names_out())
print(X.toarray())

['computer' 'harshith' 'hi' 'name' 'science' 'student']
[[0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 1 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]
 [0 0 0 0 0 0]]


NLP usecase - Sentiment Analysis

In [17]:
from sklearn.naive_bayes import MultinomialNB

texts = ["good product", "bad experience", "excellent quality", "worst item"]
labels = [1, 0, 1, 0]  # 1 = positive, 0 = negative

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(texts)

model = MultinomialNB()
model.fit(X, labels)

,"alpha alpha: float or array-like of shape (n_features,), default=1.0Additive (Laplace/Lidstone) smoothing parameter(set alpha=0 and force_alpha=True, for no smoothing).",1.0
,"force_alpha force_alpha: bool, default=TrueIf False and alpha is less than 1e-10, it will set alpha to1e-10. If True, alpha will remain unchanged. This may causenumerical errors if alpha is too close to 0... versionadded:: 1.2.. versionchanged:: 1.4 The default value of `force_alpha` changed to `True`.",True
,"fit_prior fit_prior: bool, default=TrueWhether to learn class prior probabilities or not.If false, a uniform prior will be used.",True
,"class_prior class_prior: array-like of shape (n_classes,), default=NonePrior probabilities of the classes. If specified, the priors are notadjusted according to the data.",None


In [18]:
test = ["good quality", "bad product"]
X_test = vectorizer.transform(test)

predictions = model.predict(X_test)
print(predictions)

[1 0]
